### ISSUE TITLE
Unable to get this to work with `Jest`

### ISSUE THREAD

**Issue by ibeckermayer** [jimmywarting/native-file-system-adapter#37]
Hi Jimmy,

I've been trying to get this library to work with `Jest` in order to unit test a class which uses the File System API.

I have a test which looks like

```typescript
import { getOriginPrivateDirectory } from 'native-file-system-adapter';

test('accessing the origin private file system', async () => {
  const root = await getOriginPrivateDirectory();
  // Create a new file handle.
  const fileHandle = await root.getFileHandle('Untitled.txt', { create: true });
  // Create a new directory handle.
  const dirHandle = await root.getDirectoryHandle('New Folder', {
    create: true,
  });
  // Recursively remove a directory.
  await root.removeEntry('Old Stuff', { recursive: true });

  expect(true).toBe(true);
});
```

When I first tried running it, I was getting

```
yarn run v1.22.17
$ jest /Users/ibeckermayer/webapps/packages/teleport/src/lib/tdp/sharedDirectoryManager.test.ts
 FAIL  packages/teleport/src/lib/tdp/sharedDirectoryManager.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/ibeckermayer/webapps/node_modules/native-file-system-adapter/src/es6.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import showDirectoryPicker from './showDirectoryPicker.js'
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      14 |  * limitations under the License.
      15 |  */
    > 16 | import { getOriginPrivateDirectory } from 'native-file-system-adapter';
         | ^
      17 |
      18 | test('accessing the origin private file system', async () => {
      19 |   const root = await getOriginPrivateDirectory();

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (packages/teleport/src/lib/tdp/sharedDirectoryManager.test.ts:16:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.94 s
Ran all test suites matching /\/Users\/ibeckermayer\/webapps\/packages\/teleport\/src\/lib\/tdp\/sharedDirectoryManager.test.ts/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After much googling and tinkering, I was able to induce another error after adding the following to my `jest.config.js`, which ensures that this library is transformed by my babel config:
```js
  transformIgnorePatterns: [
    '!node_modules/native-file-system-adapter/src/\\.[jt]s?$',
  ],
```

After that change, I'm instead seeing
```
    Details:

    /Users/ibeckermayer/webapps/node_modules/native-file-system-adapter/src/FileSystemWritableFileStream.js:13
    const ws = globalThis.WritableStream || (await Promise.resolve().then(() => _interopRequireWildcard(require('https://cdn.jsdelivr.net/npm/web-streams-polyfill@3/dist/ponyfill.es2018.mjs'))).then(r => r.WritableStream).catch(() => Promise.resolve().then(() => _interopRequireWildcard(require('web-streams-polyfill'))).then(r => r.WritableStream))); // TODO: add types for ws
                                                   ^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/native-file-system-adapter/src/FileSystemFileHandle.js:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.977 s
Ran all test suites matching /\/Users\/ibeckermayer\/webapps\/packages\/teleport\/src\/lib\/tdp\/sharedDirectoryManager.test.ts/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

which is complaining about this line here

https://github.com/jimmywarting/native-file-system-adapter/blob/master/src/FileSystemWritableFileStream.js#L2

I tried editing that line, making it just
```js
const ws = globalThis.WritableStream
```

which gives me the error
```
TypeError: Class extends value undefined is not a constructor or null
```
presumably meaning that `globalThis.WriteableStream` is not defined in my environment.

I then tried changing it to
```js
const ws = await import('https://cdn.jsdelivr.net/npm/web-streams-polyfill@3/dist/ponyfill.es2018.mjs').then(r => r.WritableStream).catch(() => import('web-streams-polyfill').then(r => r.WritableStream))
```
which causes me to get
```
/Users/ibeckermayer/webapps/node_modules/native-file-system-adapter/src/FileSystemWritableFileStream.js:14
    const ws = await Promise.resolve().then(() => _interopRequireWildcard(require('https://cdn.jsdelivr.net/npm/web-streams-polyfill@3/dist/ponyfill.es2018.mjs'))).then(r => r.WritableStream).catch(() => Promise.resolve().then(() => _interopRequireWildcard(require('web-streams-polyfill'))).then(r => r.WritableStream)); // TODO: add types for ws
               ^^^^^

    SyntaxError: await is only valid in async functions and the top level bodies of modules
```

That one is confusing, because as far as I know I _am_ at the top level body of a module. Anyways, perhaps you have a better understanding of what I might try next. I'm pasting the relevant bits of my configuration files below:

#### `jest.config.js`
```js
const config = require('@gravitational/build/jest/config');

process.env.TZ = 'UTC';

/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  ...config,
  globals: {
    electron: {},
  },
  transformIgnorePatterns: [
    '!node_modules/native-file-system-adapter/src/\\.[jt]s?$',
  ],
  collectCoverageFrom: [
    // comment out until shared directory is finished testing
    // '**/packages/design/src/**/*.jsx',
    '**/packages/shared/components/**/*.jsx',
  ],
  coverageReporters: ['text-summary', 'lcov'],
};
```

#### `.babelrc.js` (it uses the `if (test)` piece of the `makePresents` function)
```js
const plugins = [
  '@babel/plugin-proposal-class-properties',
  '@babel/plugin-proposal-object-rest-spread',
  '@babel/plugin-proposal-optional-chaining',
  '@babel/plugin-syntax-dynamic-import',
];

function makePresents(test = false) {
  const presents = ['@babel/preset-react', '@babel/preset-typescript'];

  if (test) {
    return [
      ['@babel/preset-env', { targets: { node: 'current' } }],
      ...presents,
    ];
  }

  return [
    [
      '@babel/preset-env',
      {
        targets:
          'last 2 chrome version, last 2 edge version, last 2 firefox version, last 2 safari version',
      },
    ],
    ...presents,
  ];
}

module.exports = {
  env: {
    test: {
      presets: makePresents(true),
      plugins: [...plugins],
    },
    development: {
      plugins: [
        ...plugins,
        ['babel-plugin-styled-components', { displayName: true, ssr: false }],
      ],
    },
  },
  presets: makePresents(),
  plugins: [
    ...plugins,
    ['babel-plugin-styled-components', { displayName: false, ssr: false }],
  ],
};
```

**Comment by milahu** [comment]
maybe fixed by #41

**Comment by jimmywarting** [comment]
All top level await was removed. 
All our internal files now depends on some config store that have all the bells and whistles it needs that NodeJS might not have ATM.

So if your env do not have any of this then you can add them yourself:
```js
{
  ReadableStream: globalThis.ReadableStream,
  WritableStream: globalThis.WritableStream,
  TransformStream: globalThis.TransformStream,
  DOMException: globalThis.DOMException,
  Blob: globalThis.Blob,
  File: globalThis.File,
}
```
This have made the package smaller.

**Comment by SevenStars07** [comment]
@ibeckermayer, I am still having this issue, did you manage to get tests working?

**Comment by milhamm** [comment]
Any updates on this? My tests are still failing
